//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "auth_permission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub module: String,
    pub name: String,
    pub hidden: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auth_user_permission::Entity")]
    AuthUserPermission,
}

impl Related<super::auth_user_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthUserPermission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
