//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "auth_group")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub confidential: bool,
    pub group_type: String,
    pub filter_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auth_group_filter::Entity")]
    AuthGroupFilter,
    #[sea_orm(has_many = "super::auth_group_roles::Entity")]
    AuthGroupRoles,
    #[sea_orm(has_many = "super::auth_group_user::Entity")]
    AuthGroupUser,
}

impl Related<super::auth_group_filter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthGroupFilter.def()
    }
}

impl Related<super::auth_group_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthGroupRoles.def()
    }
}

impl Related<super::auth_group_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthGroupUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
