//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "auth_role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auth_group_roles::Entity")]
    AuthGroupRoles,
    #[sea_orm(has_many = "super::auth_role_permissions::Entity")]
    AuthRolePermissions,
    #[sea_orm(has_many = "super::auth_role_users::Entity")]
    AuthRoleUsers,
}

impl Related<super::auth_group_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthGroupRoles.def()
    }
}

impl Related<super::auth_role_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthRolePermissions.def()
    }
}

impl Related<super::auth_role_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthRoleUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
