//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "group_filter_criteria"
)]
pub enum GroupFilterCriteria {
    #[sea_orm(string_value = "Alliance")]
    Alliance,
    #[sea_orm(string_value = "Corporation")]
    Corporation,
    #[sea_orm(string_value = "Group")]
    Group,
    #[sea_orm(string_value = "Role")]
    Role,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "group_filter_criteria_type"
)]
pub enum GroupFilterCriteriaType {
    #[sea_orm(string_value = "GreaterThan")]
    GreaterThan,
    #[sea_orm(string_value = "Is")]
    Is,
    #[sea_orm(string_value = "IsNot")]
    IsNot,
    #[sea_orm(string_value = "LessThan")]
    LessThan,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "group_filter_type")]
pub enum GroupFilterType {
    #[sea_orm(string_value = "All")]
    All,
    #[sea_orm(string_value = "Any")]
    Any,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "group_type")]
pub enum GroupType {
    #[sea_orm(string_value = "Apply")]
    Apply,
    #[sea_orm(string_value = "Auto")]
    Auto,
    #[sea_orm(string_value = "Hidden")]
    Hidden,
    #[sea_orm(string_value = "Open")]
    Open,
}
